CREATE TABLE [dbo].[Streams](
	[StreamID] [nvarchar](50) NOT NULL,
	[CurrentSequence] [bigint] NOT NULL,
	[Context] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Streams_1] PRIMARY KEY CLUSTERED 
(
	[StreamID] ASC,
	[Context] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX [IX_Streams] ON [dbo].[Streams]
(
	[StreamID] ASC,
	[CurrentSequence] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
